export const PARTNER_LIST_REQUEST = "PARTNER_LIST_REQUEST";
export const PARTNER_LIST_SUCCESS = "PARTNER_LIST_SUCCES";
export const PARTNER_LIST_RESET = "PARTNER_LIST_RESET";
export const PARTNER_LIST_FAIL = "PARTNER_LIST_FAIL";
