export const STREAM_LIST_REQUEST = "STREAM_LIST_REQUEST";
export const STREAM_LIST_SUCCESS = "STREAM_LIST_SUCCES";
export const STREAM_LIST_FAIL = "STREAM_LIST_FAIL";

export const LIKE_STREAM_REQUEST = "LIKE_STREAM_REQUEST";
export const LIKE_STREAM_SUCCESS = "LIKE_STREAM_SUCCES";
export const LIKE_STREAM_FAIL = "LIKE_STREAM_FAIL";

export const DELETE_COMMENT_REQUEST = "DELETE_COMMENT_REQUEST";
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCES";
export const DELETE_COMMENT_FAIL = "DELETE_COMMENT_FAIL";

////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////

export const UNLIKE_STREAM_REQUEST = "UNLIKE_STREAM_REQUEST";
export const UNLIKE_STREAM_SUCCESS = "UNLIKE_STREAM_SUCCES";
export const UNLIKE_STREAM_FAIL = "UNLIKE_STREAM_FAIL";

export const STREAM_DELETE_REQUEST = "STREAM_DELETE_REQUEST";
export const STREAM_DELETE_SUCCESS = "STREAM_DELETE_SUCCES";
export const STREAM_DELETE_FAIL = "STREAM_DELETE_FAIL";

export const STREAM_CREATE_RESET = "STREAM_CREATE_RESET";
export const STREAM_CREATE_REQUEST = "STREAM_CREATE_REQUEST";
export const STREAM_CREATE_SUCCESS = "STREAM_CREATE_SUCCES";
export const STREAM_CREATE_FAIL = "STREAM_CREATE_FAIL";

export const STREAM_DETAILS_REQUEST = "STREAM_DETAILS_REQUEST";
export const STREAM_DETAILS_SUCCESS = "STREAM_DETAILS_SUCCES";
export const STREAM_DETAILS_FAIL = "STREAM_DETAILS_FAIL";
export const STREAM_DETAILS_RESET = "STREAM_DETAILS_RESET";

export const CREATE_COMMENT_REQUEST = "CREATE_COMMENT_REQUEST";
export const CREATE_COMMENT_SUCCESS = "CREATE_COMMENT_SUCCES";
export const CREATE_COMMENT_FAIL = "CREATE_COMMENT_FAIL";
export const CREATE_COMMENT_RESET = "CREATE_COMMENT_RESET";

////////////////////////////////////////////////////////////////////////////
                      ///////////USER SCREEM////////////////////////
////////////////////////////////////////////////////////////////////////////

export const USER_STREAM_LIST_REQUEST = "USER_STREAM_LIST_REQUEST";
export const USER_STREAM_LIST_SUCCESS = "USER_STREAM_LIST_SUCCES";
export const USER_STREAM_LIST_FAIL = "USER_STREAM_LIST_FAIL";

export const USER_LIKE_STREAM_REQUEST = "USER_LIKE_STREAM_REQUEST";
export const USER_LIKE_STREAM_SUCCESS = "USER_LIKE_STREAM_SUCCES";
export const USER_LIKE_STREAM_FAIL = "USER_LIKE_STREAM_FAIL";

export const USER_UNLIKE_STREAM_REQUEST = "USER_UNLIKE_STREAM_REQUEST";
export const USER_UNLIKE_STREAM_SUCCESS = "USER_UNLIKE_STREAM_SUCCES";
export const USER_UNLIKE_STREAM_FAIL = "USER_UNLIKE_STREAM_FAIL";

export const USER_STREAM_DELETE_REQUEST = "USER_STREAM_DELETE_REQUEST";
export const USER_STREAM_DELETE_SUCCESS = "USER_STREAM_DELETE_SUCCES";
export const USER_STREAM_DELETE_FAIL = "USER_STREAM_DELETE_FAIL";

export const USER_STREAM_CREATE_RESET = "USER_STREAM_CREATE_RESET";
export const USER_STREAM_CREATE_REQUEST = "USER_STREAM_CREATE_REQUEST";
export const USER_STREAM_CREATE_SUCCESS = "USER_STREAM_CREATE_SUCCES";
export const USER_STREAM_CREATE_FAIL = "USER_STREAM_CREATE_FAIL";

export const USER_STREAM_DETAILS_REQUEST = "USER_STREAM_DETAILS_REQUEST";
export const USER_STREAM_DETAILS_SUCCESS = "USER_STREAM_DETAILS_SUCCES";
export const USER_STREAM_DETAILS_FAIL = "USER_STREAM_DETAILS_FAIL";
export const USER_STREAM_DETAILS_RESET = "USER_STREAM_DETAILS_RESET";

export const USER_CREATE_COMMENT_REQUEST = "USER_CREATE_COMMENT_REQUEST";
export const USER_CREATE_COMMENT_SUCCESS = "USER_CREATE_COMMENT_SUCCES";
export const USER_CREATE_COMMENT_FAIL = "USER_CREATE_COMMENT_FAIL";
export const USER_CREATE_COMMENT_RESET = "USER_CREATE_COMMENT_RESET";
